# Generated by Django 5.1.6 on 2025-05-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creatd_at',
            new_name='created_at',
        ),
    ]
